const Projects = [
	{
		_id: '01',
		image: 'assets/project/project-grid-15.jpg',
		title: 'Огтлолцол МУСК нийт 4 бүлэг',
		category: 'Кино',
		author: 'Мөнхтулга',
		userId: 'munkhtulga',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/projects/01',
		endDate: '2022-7-1',
		needed: 223050000,
		collected: 95880000,
		fundInfo3: '3',
		projectImg: '/assets/project/project-grid-15.jpg',
		projectImg2: '',
		buttonOne: '50k₮',
		buttonTwo: '100k₮',
		buttonThree: '250k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '2022 оны 7 сарын 10',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '63 дэмжигчид',
		totalRewards: '13 урамшуулал үлдсэн',
		mainTitle: 'Огтлолцол',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '02',
		image: 'assets/project/project-grid-02.jpg',
		title: 'Big Life Lil Thug E ft (Desant, Fla, Ginjin ...',
		category: 'Дуу',
		author: 'Төгөлдөр',
		userId: '',
		authorImg: 'assets/author-thumbs/03.jpg',
		url: '/projects/02',
		date: '2022 оны 04 сарын 23',
		needed: 90000000,
		collected: 39200000,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '03',
		image: 'assets/project/project-grid-03.jpg',
		title: 'Халуун Маруужин Цомог B Production',
		category: 'Дуу',
		author: 'NENE',
		userId: '',
		authorImg: 'assets/author-thumbs/06.jpg',
		url: '/projects/03',
		date: '2022 оны 04 сарын 23',
		needed: 1800000,
		collected: 1340000,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '04',
		image: 'assets/project/project-grid-11.jpg',
		title: 'Өвгөн хуурч',
		category: 'Бусад',
		author: 'Тулговски Медиа',
		userId: '',
		authorImg: 'assets/author-thumbs/11.jpg',
		url: '/projects/04',
		date: '2022 оны 04 сарын 23',
		needed: 187500000,
		collected: 211245000,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '05',
		image: 'assets/project/project-grid-05.jpg',
		title: 'Маш Нууц III: No Country for Old Men',
		category: 'Кино',
		author: 'Бат-Өлзий',
		userId: '',
		authorImg: 'assets/author-thumbs/08.jpg',
		url: '/projects/05',
		date: '2022 оны 04 сарын 23',
		needed: 187500000,
		collected: 56800087,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '06',
		image: 'assets/project/project-grid-06.jpg',
		title: 'Single Ladies IV',
		category: 'Кино',
		author: 'Ундармаа',
		userId: 'undarmaa',
		authorImg: 'assets/author-thumbs/09.jpg',
		url: '/projects/06',
		needed: 180000000,
		collected: 69800087,
		totalBackers: '28',
		endDate: '2022-06-25',
		projectImg: '/assets/project/project-details.jpg',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮'
	},
	{
		_id: '07',
		image: 'assets/project/project-grid-07.jpg',
		title: 'Цагаан Үнс: Манга номын нээлт',
		category: 'Бусад',
		author: 'Тэмлүүлэм',
		userId: '',
		authorImg: 'assets/author-thumbs/10.jpg',
		url: '/projects/07',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 335000,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '08',
		image: 'assets/project/project-grid-08.jpg',
		title: 'Playmo: All of Us Are Dead',
		category: 'Кино',
		author: 'Playmo',
		userId: '',
		authorImg: 'assets/author-thumbs/18.jpg',
		url: '/projects/08',
		date: '2022 оны 02 сарын 19',
		needed: 435000,
		collected: 15700,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '09',
		image: 'assets/project/project-grid-09.jpg',
		title: 'Аялгуу шинэ цомгын нээлт',
		category: 'Дуу',
		author: 'Вандебо',
		userId: '',
		authorImg: 'assets/author-thumbs/04.jpg',
		url: '/projects/09',
		date: '2022 оны 04 сарын 23',
		needed: 1235000,
		collected: 980700,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '10',
		image: 'assets/project/project-grid-01.png',
		title: 'ThunderZ: Street Дуу',
		category: 'Дуу',
		author: 'Toonot',
		userId: '',
		authorImg: 'assets/author-thumbs/05.jpg',
		url: '/projects/10',
		date: '2022 оны 04 сарын 23',
		needed: 2975000,
		collected: 2380000,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '11',
		image: 'assets/project/project-grid-08.png',
		title: 'Зоригт ft Хишигдалай: Санаж байна уу',
		category: 'Дуу',
		author: 'Зоригт',
		userId: '',
		authorImg: 'assets/author-thumbs/17.jpg',
		url: '/projects/11',
		date: '2022 оны 04 сарын 23',
		needed: 4875000,
		collected: 2500090,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '12',
		image: 'assets/project/project-grid-13.jpg',
		title: 'Худалдагч Охин II',
		category: 'Кино',
		author: 'Nomadia Pictures',
		userId: '',
		authorImg: 'assets/author-thumbs/02.jpg',
		url: '/projects/12',
		date: '2022 оны 02 сарын 11',
		needed: 19875000,
		collected: 12900000,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '13',
		image: 'assets/project/project-grid-14.jpg',
		title: 'Нийслэл Хүүхэн II-р бүлэг',
		category: 'Кино',
		author: 'Nomadia Pictures',
		userId: '',
		authorImg: 'assets/author-thumbs/02.jpg',
		url: '/projects/13',
		date: '2022 оны 01 сарын 22',
		needed: 19875000,
		collected: 1235000,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '14',
		image: 'assets/project/project-grid-12.jpg',
		title: 'Крипто гудамжны чононууд',
		category: 'Бусад',
		author: 'MNFT',
		userId: '',
		authorImg: 'assets/author-thumbs/13.jpg',
		url: '/projects/14',
		date: '2022 оны 05 сарын 23',
		needed: 1875000,
		collected: 1250000,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '15',
		image: 'assets/project/project-grid-10.jpg',
		title: '"Rebirth" цуглуулга',
		category: 'Бусад',
		author: 'Тэнүүн Tenne',
		userId: '',
		authorImg: 'assets/author-thumbs/14.jpg',
		url: '/projects/15',
		date: '2022 оны 04 сарын 23',
		needed: 23075000,
		collected: 13500030,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '16',
		image: 'assets/project/project-grid-17.jpg',
		title: 'Хавтас Хэрэг ОАУСК төсөл',
		category: 'Кино',
		author: 'Nomadia Pictures',
		userId: '',
		authorImg: 'assets/author-thumbs/02.jpg',
		url: '/projects/16',
		date: '2022 оны 01 сарын 18',
		needed: 31875000,
		collected: 4700000,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '17',
		image: 'assets/project/project-grid-18.jpg',
		title: 'Миний Хайртай Пабло УСК',
		category: 'Кино',
		author: 'Хүлэгү пикчерс',
		userId: '',
		authorImg: 'assets/author-thumbs/16.jpg',
		url: '/projects/17',
		date: '2022 оны 04 сарын 23',
		needed: 9875000,
		collected: 510000,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	},
	{
		_id: '18',
		image: 'assets/project/project-grid-16.jpg',
		title: 'MESA Nomadic Masters тэмцээн',
		category: 'Бусад',
		author: 'MESA',
		userId: '',
		authorImg: 'assets/author-thumbs/15.jpg',
		url: '/projects/18',
		date: '2022 оны 02 сарын 28',
		needed: 9000000,
		collected: 5600000,
		fundInfo1: '',
		fundInfo2: '',
		fundInfo3: '',
		projectImg: '',
		projectImg2: '',
		buttonOne: '20k₮',
		buttonTwo: '70k₮',
		buttonThree: '100k₮',
		buttonFour: '500k₮',
		buttonFive: '1сая₮',
		rewardsImg: '',
		rewardDeliveryDate: '',
		bronzeReward: '',
		silverReward: '',
		goldReward: '',
		totalBacks: '',
		totalRewards: '',
		mainTitle: '',
		story1: '',
		mainTitle2: '',
		story2: '',
		bullet1: '',
		bullet2: '',
		bullet3: '',
		bullet4: '',
		story3: ''
	}
]

export default Projects
